[package]
name = "jinnd-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
jinnd-api = { path = "../jinnd-api" }
jinnd-context = { path = "../jinnd-context" }
jinnd-effects = { path = "../jinnd-effects" }
jinnd-events = { path = "../jinnd-events" }
jinnd-fiber = { path = "../jinnd-fiber" }
jinnd-ledger = { path = "../jinnd-ledger" }
jinnd-loader = { path = "../jinnd-loader" }
jinnd-registry = { path = "../jinnd-registry" }
jinnd-wasm = { version = "0.0.1", path = "../jinnd-wasm" }
serde = "1.0.219"
tokio = { version = "1.47.1", features = ["macros", "rt", "sync"] }
tokio-util = "0.7.19"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt", "sync"] }
wit-component = "0.233.0"
